/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.WelcomeController;
import dao.AccessBackofficeDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Formation
 */
public class WelcomeView extends javax.swing.JDialog {

    private WelcomeController welcomeController;
    private JOptionPane optionPane = new JOptionPane();

    // 
    public WelcomeView(WelcomeController welcomeController) {
        this.welcomeController = welcomeController;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        TextFieldLogin = new javax.swing.JTextField();
        PasswordFieldEnter = new javax.swing.JPasswordField();
        Connecton = new javax.swing.JButton();
        WebSite = new javax.swing.JLabel();
        WelcomeLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        Login.setText("Identifiant");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 4, 5, 0);
        jPanel1.add(Login, gridBagConstraints);

        Password.setText("Mot De Passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 5, 0);
        jPanel1.add(Password, gridBagConstraints);

        TextFieldLogin.setMaximumSize(new java.awt.Dimension(150, 20));
        TextFieldLogin.setMinimumSize(new java.awt.Dimension(150, 20));
        TextFieldLogin.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 11;
        jPanel1.add(TextFieldLogin, gridBagConstraints);

        PasswordFieldEnter.setMaximumSize(new java.awt.Dimension(150, 20));
        PasswordFieldEnter.setMinimumSize(new java.awt.Dimension(150, 20));
        PasswordFieldEnter.setPreferredSize(new java.awt.Dimension(150, 20));
        PasswordFieldEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel1.add(PasswordFieldEnter, gridBagConstraints);

        Connecton.setText("Connexion");
        Connecton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(23, 7, 23, 7);
        jPanel1.add(Connecton, gridBagConstraints);

        WebSite.setText("https://www.airafpa.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        jPanel1.add(WebSite, gridBagConstraints);

        WelcomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boo.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(WelcomeLogo, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        Help.setText("Help");

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Help.add(About);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void PasswordFieldEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldEnterActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutActionPerformed

    private void ConnectonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectonActionPerformed
        // TODO add your handling code here:

        String login = this.TextFieldLogin.getText();
        String password = String.valueOf(this.PasswordFieldEnter.getPassword());
        
        // Session is blocked
        if (!this.welcomeController.checkTryNumber()) {
            this.optionPane.showMessageDialog(this, this.welcomeController.getErrorMessageContent(), this.welcomeController.getErrorMessageTitle(), this.optionPane.ERROR_MESSAGE);
            System.exit(0);
        } 
        // login or password is incorrect
        else if (!this.welcomeController.checkLoginPassword(login, password)) {
            this.optionPane.showMessageDialog(this, this.welcomeController.getErrorMessageContent(), this.welcomeController.getErrorMessageTitle(), this.optionPane.WARNING_MESSAGE);
        } else {
            this.TextFieldLogin.setText("");
            this.PasswordFieldEnter.setText("");
            this.dispose();

            if (this.welcomeController.getHasChanged()) {

                boolean confirmationPassword = false;

                do {
                    String newPassword = JOptionPane.showInputDialog(
                            this,
                            "Merci de saisir un nouveau mot de passe",
                            "New password",
                            JOptionPane.WARNING_MESSAGE
                    );

                    String newPasswordConfirm = JOptionPane.showInputDialog(
                            this,
                            "Merci de confirmer le nouveau mot de passe",
                            "Password's confirmation",
                            JOptionPane.WARNING_MESSAGE
                    );
                    System.out.println(newPassword);
                    System.out.println(newPasswordConfirm);
                    if (newPassword.equals(newPasswordConfirm)) {
                        confirmationPassword = true;

                    }
                } while (!confirmationPassword);
            }
        }
    }//GEN-LAST:event_ConnectonActionPerformed

   
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccessBackofficeDAO accessBackofficeDAO = new AccessBackofficeDAO();
                WelcomeController welcomeController = new WelcomeController(accessBackofficeDAO);
                WelcomeView dialog = new WelcomeView(welcomeController);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton Connecton;
    private javax.swing.JMenu Help;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordFieldEnter;
    private javax.swing.JTextField TextFieldLogin;
    private javax.swing.JLabel WebSite;
    private javax.swing.JLabel WelcomeLogo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
